services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Acha105#
      MYSQL_DATABASE: book_management
      MYSQL_USER: root
      MYSQL_PASSWORD: Acha105#
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: book-review-api
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Acha105#
      DB_NAME: book_management
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: review
      REFRESH_SECRET: your-refresh-secret
    volumes:
      - .:/app
    command: sh -c "npm run start"

volumes:
  mysql_data:
